### PR TITLE
Fix issue #38, invalid multipartBoundary

### LINKED ISSUE #38: multipartBoundary pointer not correct
https://github.com/chmorgan/libesphttpd/blob/9634e28f6197da0af41d9b67e9c1c9e526d1d3ec/core/httpd.c#L734

I found there was a change in commit 21fb7796d1d4e0a514416b4d7198d79c3e2a654b where you removed two character overrides with '-'. I am a little confused about both states. 

We are searching for "boundary=" ->b and later set the pointer to b+7. The length of our search subject is 9 so our buffer will contain for example "y=----WebKitFormBoundarywrAqgDbLLFmgN4Zn". Is there a reason the y= have previously been overwritten with hyphens? Should we exchange the 7 for strlen("boundary=")?

EDIT: I have found in this specification https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html that the two hyphens are mandatory. While the original solution was not well designed it correctly "prepended" two hyphens

### PR DESCRIPTION
**Pull request by PaulFreund**
This commit fixes #38

### CODE REVIEW

**Review by chmorgan — COMMENTED** [review]
Your comment about users having to prepend the hyphens is a little confusing. Is there an example of usage of this multipart functionality somewhere? I'm sure I wouldn't know what to do here so I'm guessing a new user wouldn't either. Should we document that requirement somewhere?

**Comment by PaulFreund** [comment]
I have written a routine that uploads ota updates to MicroSD (unfortunately proprietary) via HTTP POST. In this scenario I have to detect where in the HTTP body the binary data starts after the multipart boundary and where it ends with one. In the post buffer the value of the boundary field is used with two prepended hyphens:

    ----WebKitFormBoundarywrAqgDbLLFmgN4Zn

becomes
 
    ------WebKitFormBoundarywrAqgDbLLFmgN4Zn

This is also what the original code did, in the buffer was:

    boundary=----WebKitFormBoundarywrAqgDbLLFmgN4Zn

and after replacing the buffer was:

    boundar------WebKitFormBoundarywrAqgDbLLFmgN4Zn

and then the multipartBoundary pointer was set to position 7 which is

    ------WebKitFormBoundarywrAqgDbLLFmgN4Zn

Now after that commit the user will find ----WebKitFormBoundarywrAqgDbLLFmgN4Zn in the buffer and has to add the two hyphens himself when searching for it in POST data. I don't know if this is in the scope of this library. If it should be we need to add an upload function.

**Comment by chmorgan** [comment]
@PaulFreund ahh that makes it a little bit clearer.

Let me merge this in as its an improvement, thanks for the PR!

**Comment by phatpaul** [comment]
@PaulFreund would you please implement the multipart handling in my improved version of the vfs upload function?

I have a todo listed in it where that multipart stuff is missing.  https://github.com/phatpaul/libesphttpd/blob/vfs_upload/util/esp32_httpd_vfs.c#L355

We need to both extract the filename parameter, and delimit the file data start and stop.

**Comment by phatpaul** [comment]
@PaulFreund would you please add your implementation of searching for the file data start/stop in a multipart/form-data to the improved vfs upload function?  (I've improved and tested the old one.  I'm working on a PR, but would be great to handle POSTed form files as well.)

We also need to find the value of the "filename" parameter in the form.  I left a todo here for that:
https://github.com/phatpaul/libesphttpd/blob/vfs_upload/util/esp32_httpd_vfs.c#L355

**Comment by phatpaul** [comment]
Sorry for double-post.  My comments seem to disappear after I post them.

**Pull request merged**
