### PR TITLE
remove espfs from this repo

### PR DESCRIPTION
**Pull request by phatpaul**
See prior discussion: https://github.com/jkent/esp32-espfs/issues/1
To take advantage of new espfs improvements contributed by others since being introduced by sprite_tm in this libesphttpd. 

Users may include espfs as a submodule at /components/espfs, which libesphttpd can then use.
https://github.com/phatpaul/espfs/tree/libesphttpd
(will link to @jkent jkent/esp32-espfs if he agrees to maintain it)

Example usage:
https://github.com/phatpaul/esphttpd-freertos/tree/espfs_submodule

Depends on my changes to:
- components/espfs @ b87f89a

Todo:
- documentation on how to include espfs
- further testing
- I assume the Makefile.esp8266 and CMake are broken, but I don't use those.

Don't merge this until those submodules upstream repos merge the required changes.

### CODE REVIEW

**Comment by chmorgan** [comment]
@phatpaul let me know when you'd like me to review, if you'd like me to review.

**Comment by jkent** [comment]
@phatpaul I'm alright with maintaining esp32-espfs.

**Comment by phatpaul** [comment]
@chmorgan yes please review and merge when you have time.  I've got it working for my project and need to keep moving...

**Comment by chmorgan** [comment]
@phatpaul merged!

**Pull request merged**
