### PR TITLE
HttpCgiExArg: better handling of CgiArg/CgiArg2 arguments

### PR DESCRIPTION
**Pull request by jkent**
This allows routes like "/vfs/*" to map to "/spiffs/" instead of "/spiffs/vfs/" when cgiArg2 is a true value.

### CODE REVIEW

**Comment by phatpaul** [comment]
Hey @jkent I'm already using cgiArg2 in my project to customize the HTTP headers.  
I have been meaning to do a pull-request for it...
Anyway maybe we can combine these options in a way that is future-proof?

Here's the basics of what I did:
```#c
static void customHeaders_cacheForever(HttpdConnData *connData)
{
	httpdHeader(connData, "Cache-Control", "max-age=365000000, public, immutable");
	httpdHeader(connData, "Content-Type", httpdGetMimetype(connData->url));
	//printf("Test customHeaders_cacheForever!\n");
}
cgiEspFsHookOptions CgiGetOptionsCacheForever = {
	.customHeadersFnPtr = &customHeaders_cacheForever,
};
static void customHeaders_cacheNever(HttpdConnData *connData)
{
	httpdHeader(connData, "Cache-Control", "no-store, must-revalidate, no-cache, max-age=0");
	httpdHeader(connData, "Expires", "Mon, 01 Jan 1990 00:00:00 GMT"); //  This one might be redundant, since modern browsers look for "Cache-Control".
																	   //printf("Test customHeaders_cacheNever!\n");
}
cgiEspFsHookOptions CgiGetOptionsCacheNever = {
	.customHeadersFnPtr = &customHeaders_cacheNever,
};
```
and in route:
```
HttpdBuiltInUrl builtInUrls[] = {
...
	ROUTE_CGI_ARG2("/static/*", cgiEspFsHook, NULL, &CgiGetOptionsCacheForever),

	ROUTE_CGI_ARG2("*", cgiEspVfsGet, FS_BASE_PATH HTML_ROOT_PATH "/", &CgiGetOptionsCacheNever),
```
and some changes in libesphttpd (needs rebase):
https://github.com/chmorgan/libesphttpd/commit/f701bca3fef7d671e8ed83fe1d42a5dfd8815a05

**Comment by jkent** [comment]
Yeah, combining these features would be for the best.  Should I wait for your PR?  I don't have a pressing need for this, it was just a nicety with multiple espfs support.

**Comment by phatpaul** [comment]
What do you think would be the best way to implement this so that it is backward and forward compatible?  
Ideally we should be able to add optional parameters in the future, but code written prior should not be broken by it.

Perhaps we define a structure in httpd.h (or separate structures per cgi file) that can grow over time with additional options:
```
typedef struct {
	void (*customHeadersFnPtr)(HttpdConnData *connData);
        bool stripRoute;
        //... keep adding more members as needed
} cgiOptions;
```
We need a way to initialize the struct that is future-proof.

- Any options that are null are assumed unset.  And initialize it to all zeros like

```cgiOptions myCgiOptions = {0};```

- Or, if we need defaults that are not null:

```cgiOptions myCgiOptions = CGI_OPTIONS_DEFAULT();```

where the defaults are defined in httpd.h
```
#define CGI_OPTIONS_DEFAULT() { \
    .customHeadersFnPtr = null, \
    .stripRoute = FALSE, \
};
```

Does this add overhead if not using some of the options, or can the compiler see that they are constants and optimize?

**Comment by jkent** [comment]
Either one works, the first turns into a memset, the second is (unoptimized) memcpy from flash to ram.  I prefer the former, because defaults cannot be changed inadvertently.

**Comment by jkent** [comment]
Do you want me to go ahead and implement this?

~~I'm also wondering if I should do the same thing for espFsInit() since the functions signatures had to change with the removal of the static fs pointer...  Might as well do it now while things are breaking there, right?~~  Went ahead and did this.

**Comment by jkent** [comment]
Oh, also, you don't need to initialize to zero if you're setting a single value, at least with gcc, the entire struct gets initialized to zero.

**Comment by chmorgan** [comment]
@jkent the c standard says that global variables are initialized to zero at program startup.

**Comment by jkent** [comment]
Oh yes, I was thinking about on the stack... passing to a function.  Forgot routes were global for a little bit.  Yes, that makes sense.

**Comment by phatpaul** [comment]
@jkent Yeah feel free to implement it if you've got time, thanks.  I'll be happy to test.

**Comment by jkent** [comment]
Hey @phatpaul, I've made these changes, they are ready for review!  I haven't had a chance to test them thoroughly yet, and I have some changes I want to make for index resolution.  But with my simple test of the basepath it works.

**Comment by jkent** [comment]
I'm not sure what I did, but I'm getting build issues with CMake now.  I'll come back to this later this evening.  Sorry for the noise!

**Comment by jkent** [comment]
Resolved.  I forgot the CMake stuff hasn't been merged yet and was confused by the error message idf.py build was giving.  We're all good now!

**Comment by phatpaul** [comment]
Finally getting around to testing this.  It requires several other components updated to build.

Also a crash if ex->basepath not set.  See my PR to your PR: https://github.com/jkent/libesphttpd/pull/1

**Comment by jkent** [comment]
Great, thanks

**Comment by phatpaul** [comment]
@jkent please merge the PRs to your branch and then rebase this on chmorgan:master so I can do a final review.

**Comment by jkent** [comment]
I'm afraid of doing a rebase onto chmorgan:master.  I will do some testing tomorrow.  Sorry about my absense.

**Comment by phatpaul** [comment]
I've been using this successfully for a while now.  I think it's ready to merge.  @jkent please merge the pull request https://github.com/jkent/libesphttpd/pull/4

**Review by phatpaul — APPROVED** [review]

**Pull request merged**
