### PR TITLE
Fix VFS File Name Buffer Handling

### PR DESCRIPTION
**Pull request by tidklaas**
util/esp32_httpd_vfs.c:
 - initialise file name buffer before using strcat()
 - fix inconsistent use of tabs/spaces for indentation

### CODE REVIEW

**Comment by chmorgan** [comment]
Thanks for the PR!

**Comment by phatpaul** [comment]
Hi @tidklaas 
Did you test the cgiEspVfsUpload() function?  I'm not saying it worked before your change, but it doesn't work for me.  Please see my bug report: https://github.com/chmorgan/libesphttpd/issues/44

**Comment by tidklaas** [comment]
No, I have only used the download function and ran into the issue with the uninitialised filename buffer. Since the upload function had the same bug, I fixed it there too.

**Comment by phatpaul** [comment]
OK, just checking to make sure I don't break what was working for someone else.

Seems the original author contributed these functions "as is" and untested.  https://github.com/chmorgan/libesphttpd/pull/24

**Pull request merged**
