### PR TITLE
vfs: determine gzip compression from magic bytes

### PR DESCRIPTION
**Pull request by jkent**
* use gzip magic bytes on html, css, js, and svg files to determine if file is gzip compressed.
* ~~implement espFsSeek~~
* ~~implement espfs_vfs for mounting espfs~~

### CODE REVIEW

**Comment by phatpaul** [comment]
@jkent Please see my PR #61 as we want to remove espfs implementation from this repo in favor of linking to yours.

So I see you updated some espfs files in this repo (which will be removed), did you also make these changes to your repo?  jkent/esp32-espfs 

I think the only espfs files which will remain is util/esp32_httpd_vfs.c /.h

**Comment by jkent** [comment]
@phatpaul I needed these changes to properly test the code as a single unit.  I'll update the esp32-espfs repo now.

The only thing I believe I changed is esp_espfs_init, requiring an explicit call to espFsInit()

**Comment by phatpaul** [comment]
Ok cool.  I'll try to test it this week.  Thanks for contributing!

**Comment by dmcnaugh** [comment]
I like the idea of using the magic bytes, but I don’t think this should just replace the original code. It would be better to see both strategies work side by side.
When I wrote this code it was to enable **any** file on the VFS to be gzipped  and the code works as a fall thru ie. if the desired file doesn’t exist, check for a gzipped (*.gz) copy and serve that.
This enables a workflow where your you test with uncompressed files and then later, simply gzip **any** large files in the VFS to optimise. I use this all the time and you will break it with this change as it is currently proposed.
What you have added is nice but should be in addition to, not instead of the existing strategy.

**Comment by phatpaul** [comment]
@dmcnaugh I agree.  

Also, gzip header should not be limited to .js, .css, .html, .svg files.

Also what happens in the case that you want to download a file.gz but don't want the browser to decompress it- in that case the server should not send the gzip header?

How about this?
```c
if (requested file extension == *.gz)
{
  // This case user want's to download a .gz file, we shouldn't tell the browser to decompress it.
  serve file without gzip header;
}
else
{
  if (file is found)
  {
    if (file has gzip magic)
    {
       serve file with gzip header;
    }
    else // file not gzip
    {
      serve file without gzip header;
    }
  }
  else // file not found
  {
    if (file + ".gz" is found)
    {
      // don't need to check magic bytes in this case
      serve file with gzip header;
    }
    else
    {
      404 not found;
    }
  }
}
```

**Comment by jkent** [comment]
@dmcnaugh Okay, this makes sense.

@phatpaul I limit to certain file extensions because there is a chance a binary file might match the two magic bytes.  Text files, on the other hand, don't have this possibility.  If there were more bytes to match I'd consider it.  Otherwise the logic you showed is fine.

**Comment by dmcnaugh** [comment]
I agree the magic bytes test should be limited to some scope to avoid false positives with binary files.
I can’t recall if libesphttpd has a good enough MIME system to handle this, but it would be ideal to apply it to all text/* MIME types. This takes care of everything except svg files that belong to image/*

**Comment by jkent** [comment]
@dmcnaugh This sounds reasonable, except the default MIME type is text/plain.  I don't like the idea of it checking magic bytes in this case.

**Comment by dmcnaugh** [comment]
What problem do you see with text/plain ? Not being close to the problem I can’t think of anything,

**Comment by jkent** [comment]
Because the default is text/plain, a request for something.bin gets a mime type of text/plain.  It's not reliable for a magic byte check.

**Comment by dmcnaugh** [comment]
Ok thanks I didn’t know that. Hard coding the desired file extensions as you have makes it work for your needs and that’s as good as it needs to be.

**Comment by jkent** [comment]
@phatpaul have you had the chance to test this out?

**Comment by jkent** [comment]
I'm going to create a new pull request using a feature branch, closing this one

**Comment by phatpaul** [comment]
Sorry I got half-way writing an example in https://github.com/chmorgan/esphttpd-freertos/pull/12 to test it earlier this week.  Hopefully I can complete it this week.

**Pull request closed without merging**
