### PR TITLE
Split HTTP server task into init, process and deinit to allow executing in custom run loop

### PR DESCRIPTION
**Pull request by PaulFreund**
Reordered the task code to be split in init, process and deinit. That way custom process models are possible where processing is manually triggered

### CODE REVIEW

**Comment by PaulFreund** [comment]
Please don't merge yet, I just recognized that the process is still blocking. I need to add a second commit to bring that option

**Comment by PaulFreund** [comment]
Added a second commit. As ServerTaskContext is normally initialized to all zeroes the pointer to the timeout struct is also NULL which means select will block as usual. This behaviour can now be overwritten by setting the selectTimeout pointer in the context before running.

**Comment by chmorgan** [comment]
@PaulFreund looks like an interesting improvement to me, I'm guessing you want to control the context the server runs in for your purposes? If everything is working and you are happy with the result feel free to merge.

**Comment by PaulFreund** [comment]
Yes, I have written an application framework that runs in it's own run loop in one freertos task to be compatible to environments that don't have tasks. In my scenario the Webserver is triggered as part of that run loop. I have tested both task based processing and "self processing" and am happy with the result. Would be nice if you merge it :)

**Pull request merged**
