### PR TITLE
update for new espfs api

### PR DESCRIPTION
**Pull request by jkent**

### CODE REVIEW

**Comment by phatpaul** [comment]
So this PR goes with https://github.com/chmorgan/esphttpd-freertos/pull/18 ?
They should be merged at the same time.

**Comment by chmorgan** [comment]
Is it ready to merge?

**Comment by jkent** [comment]
I've been using it in development with no problems.  I think its as good as its going to get!

**Comment by jkent** [comment]
Yes to both at the same time.

**Pull request merged**
