### PR TITLE
option to default to single request per connection

### PR DESCRIPTION
**Pull request by jkent**
See #59

### CODE REVIEW

**Comment by chmorgan** [comment]
Hi @jkent is this still an active PR? We can merge if it's ready.

**Comment by jkent** [comment]
Hey @chmorgan I'll take a look in a few days, I just got out of the
hospital, trying to take recovery one day at a time.

**Comment by chmorgan** [comment]
@jkent I wish you the best of recovery and no worries, its just a pull request!

**Comment by jkent** [comment]
@chmorgan thanks for the kind words.  I'm going to work on espfs before working on this.  I'm taking the brave task of working on a CMake build system for it.  https://github.com/jkent/esp32-espfs/issues/7

**Comment by jkent** [comment]
This PR is still valid.

**Comment by chmorgan** [comment]
@jkent would you like me to merge it to master?

**Comment by jkent** [comment]
Yes please

**Pull request merged**
